"""commit message

Revision ID: 4e3bf4ab03e6
Revises: 8ef17c84a987
Create Date: 2025-12-25 22:20:13.722826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e3bf4ab03e6'
down_revision: Union[str, Sequence[str], None] = '8ef17c84a987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False, comment='The unique identifier for the user'),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Indicates user pet is given for stay'),
    sa.Column('first_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False, comment='The first name of the user'),
    sa.Column('last_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False, comment='The last name of the user'),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False, comment='The email address of the user'),
    sa.Column('phone', sa.VARCHAR(length=13), autoincrement=False, nullable=True, comment='The phone number of the user'),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False, comment='The date of birth of the user'),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='The gender of the user'),
    sa.Column('profile_picture_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment="The URL of the user's profile picture"),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False, comment='The timestamp when the user account was created'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='The timestamp when the user account was last updated'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone', name=op.f('user_phone_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
