"""Create user table

Revision ID: 8ef17c84a987
Revises: 
Create Date: 2025-12-22 00:36:25.999065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef17c84a987'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='The unique identifier for the user'),
    sa.Column('active', sa.Boolean(), nullable=False, comment='Indicates user pet is given for stay'),
    sa.Column('first_name', sa.String(length=60), nullable=False, comment='The first name of the user'),
    sa.Column('last_name', sa.String(length=60), nullable=False, comment='The last name of the user'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='The email address of the user'),
    sa.Column('phone', sa.String(length=13), nullable=True, comment='The phone number of the user'),
    sa.Column('date_of_birth', sa.Date(), nullable=False, comment='The date of birth of the user'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='The gender of the user'),
    sa.Column('profile_picture_url', sa.String(length=255), nullable=True, comment="The URL of the user's profile picture"),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='The timestamp when the user account was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='The timestamp when the user account was last updated'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
